### ISSUE TITLE
Merge with https://github.com/tracecompass/tracecompass/tree/master/common/org.eclipse.tracecompass.common.core/annotations

### ISSUE THREAD

**Issue by kwin** [lastnpe/eclipse-null-eea-augments#10]
Tracecompass has also maintained some external annotations for quite some libraries in the past. It seems right now much more extensive than this approach. Could you just merge all changes from https://github.com/tracecompass/tracecompass/tree/master/common/org.eclipse.tracecompass.common.core/annotations?
Not sure whether the license would allow that though.

**Comment by vorburger** [comment]
@kwin or anyone else interested (@maggu2810 ?) - terribly sorry for replying only now, but finally picking this project up...

We would love to get these in. LICENSE should not be an issue, as both projects are EPL.

I've made a start with the JDK ones in https://github.com/lastnpe/eclipse-null-eea-augments/pull/15 and https://github.com/lastnpe/eclipse-null-eea-augments/pull/17 (NB due to #16 I skipped merging java.lang.String, java.util.Collections and java.util.Map and kept my original ones, and did not merge with tracecompass' - review feedback on #17 would be welcome!).

Would you like to add the other ones? Specifically tracecompass' [Guava](https://github.com/tracecompass/tracecompass/tree/master/common/org.eclipse.tracecompass.common.core/annotations/com/google/common), [Apache Commons](https://github.com/tracecompass/tracecompass/tree/master/common/org.eclipse.tracecompass.common.core/annotations/org/apache/commons) would be interesting, useful and very welcome!

BTW: As per README, you can become a committer on this project with x3 PRs! ;-)
