### ISSUE TITLE
Add unit test which parses the files to make sure they are valid

### ISSUE THREAD

**Issue by digulla** [lastnpe/eclipse-null-eea-augments#105]
Please add a unit test that tries to read all *.eea files and makes sure the syntax is valid.

Background: In my Eclipse (since 2020-06 or 4.16), the annotate menu is broken and doesn't allow me to create annotations anymore (nothing happens when I select the item and the child menus which were there before are missing).

So I need a way to validate the hand-crafted annotations.

**Comment by jason-faust** [comment]
Do you happen to know which annotation is causing the failure?

**Comment by jason-faust** [comment]
@J-N-K I started writing a new validator to address this. Can you take a look at branch eea-validate and give some feedback / opinion on where it stands?

**Comment by J-N-K** [comment]
There is a validation, it checks the signatures of the annotations against the siganture of the method. Accidentally I created a wrong annotation (while trying to solve #116) and the build failed. Can you show which malformed annotation is not detected?

**Comment by jason-faust** [comment]
@J-N-K The test code felt too hacky for me, the way it was wired. It deferred testing of the annotations till the full build, instead of a project by project basis.

Also, I'm not sure how to resolve the 'verify signature' part of the old validator. We've said we don't care if the annotation match the library version any longer, so there's no logical way to say if a signature is good or not, beyond syntax.  Do you think Syntax will be sufficient?

**Comment by J-N-K** [comment]
I don't know much about the development of maven plugins, if you can't get the declared dependencies, I would guess that having a syntax check for the single project build and having the signature check in the full build is fine.

**Comment by sebthom** [comment]
This has been implemented as part of https://github.com/lastnpe/eclipse-null-eea-augments/pull/168
