### ISSUE TITLE
Copyright ?

### ISSUE THREAD

**Issue by vorburger** [lastnpe/eclipse-null-eea-augments#174]
Does anyone reading this have any opinions what we want to adopt as the convention (rule) about Copyright in the LastNPE.org community & this repo?

As of right now, [this repo doesn't yet have any files with copyright headers](https://github.com/search?q=repo%3Alastnpe%2Feclipse-null-eea-augments%20copyright&type=code). The Eclipse plugin has a few _"Copyright (c) 2016 Red Hat, Inc. and others. All rights reserved."_ (and a bogus one in the `feature.xml`), [see here](https://github.com/search?q=org%3Alastnpe%20copyright&type=code).

In #168 the new `generator` tool that's being proposed uses _"SPDX-FileCopyrightText: © Vegard IT GmbH (https://vegardit.com) and others."_ (FTR: I don't mean to hold up merging that PR, but am starting this as a separate parallel discussion.)

All good? Or do want to have e.g. (something like) _"Copyright 2024 The LastNPE.org `<https://www.lastnpe.org>` Authors"_ sort of thing?

@sebthom

**Comment by sebthom** [comment]
I haven't seen any of the Eclipse projects using a pattern like `Copyright XYZ The Eclipse Foundation <https://www.eclipse.org/> Authors`. If the goal still is to become an Eclipse project one day (which I hope) this should maybe be clarified with someone from legal at Eclipse.

**Comment by kwin** [comment]
The copyright by default is with the authors (=committers if not stated otherwise) of a specific file. It feels weird to contribute the copyright to another entity this repo is not (yet) affiliated with. Also I don't think this is necessary for Eclipse to accept a potential contribution (compare e.g. with https://github.com/eclipse-m2e/m2e-core/blob/master/org.eclipse.m2e.core/src/org/eclipse/m2e/core/embedder/IComponentLookup.java). What matters most is IMHO the license!

**Comment by sebthom** [comment]
@vorburger I think this can be closed since you merged the code?

**Comment by sebthom** [comment]
I think this is solved. Reopen if required.
